name: Multi-Platform Test

on:
  push:
    branches: [ main ]
    paths:
      - 'benchplot/**'
      - 'examples/**'

  pull_request:
    branches: [ main ]
    paths:
      - 'benchplot/**'
      - 'examples/**'

  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      shell: bash

    - name: Run tests
      run: |
        cargo test --release

        # Run examples
        for example in examples/*; do
          if [ -f "$example/Cargo.toml" ]; then
            cargo run --release --manifest-path "$example/Cargo.toml"
          fi
        done
      shell: bash
